
[colors]
draw_bold_text_with_bright_colors = true

# [colors.bright]
# black = "#414868"
# blue = "#7aa2f7"
# cyan = "#7dcfff"
# green = "#73daca"
# magenta = "#bb9af7"
# red = "#f7768e"
# white = "#c0caf5"
# yellow = "#e0af68"
# 
# [colors.normal]
# black = "#414868"
# blue = "#7aa2f7"
# cyan = "#7dcfff"
# green = "#73daca"
# magenta = "#bb9af7"
# red = "#f7768e"
# white = "#c0caf5"
# yellow = "#e0af68"

# [colors.primary]
# background = "#1a1b26"
# foreground = "#a9b1d6"


[colors.primary]
background = "#000000"
foreground = "#00FF00"

[cursor]
style = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
family = "Hack Nerd Font"
style = "Bold"

[font.offset]
x = 0
y = -1

[scrolling]
history = 5000

[window]
title = "HackAcritty"

[window.padding]
x = 5
y = 5
